name: flutter_ali_auth
description: Flutter Ali Auth Plugin 阿里云一键登录Flutter插件
repository: https://github.com/fluttercandies/flutter_ali_auth
version: 0.7.1
homepage: https://github.com/fluttercandies/flutter_ali_auth

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1

flutter:
  plugin:
    platforms:
      android:
        package: com.fluttercandies.flutter_ali_auth
        pluginClass: FlutterAliAuthPlugin
      ios:
        pluginClass: FlutterAliAuthPlugin
